import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Nabar/page";
import Hero from "@/components/Hero/page";
import About from "@/components/About/page";
import Contact from "@/components/Contact/page";
import Service from "@/components/Service/page";
import BookTable from "@/components/BookTable/page";
import FoodMenu from "@/components/FoodMenu/page";
import TeamMember from "@/components/TeamMember/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        <Hero></Hero>
        <TeamMember></TeamMember>
        <FoodMenu></FoodMenu>
        <About></About>
        <BookTable></BookTable>
        <Service></Service>
        <Contact></Contact>
        {children}
      </body>
    </html>
  );
}
